In [1]:
import os
import pandas as pd

In [27]:
rootdir = os.getcwd()
files_tsv = []
for (dirpath, dirnames, filenames) in os.walk(os.path.join(rootdir, 'assets\\events_set')):
    for file in filenames:
        if file.endswith('.tsv') and not file.startswith('.'):
            files_tsv.append(os.path.join(dirpath, file))

In [72]:
df_combined = pd.DataFrame()
event_types = ['earthquake', 'fire', 'flood', 'hurricane']
for file in files_tsv:
    df_new = pd.read_csv(file, sep='\t')
    file_name = file.split('\\')[-1]
    df_new['file_name'] = file_name
    event, data_type = file_name.rsplit('_', 1)
    df_new['event'] = event
    df_new['year'] = event.split('_')[-1]
    df_new['year'] = df_new['year'].astype(int)
    for e in event_types:
        if e in event:
            event_type = e
            break
    df_new['event_type'] = event_type
    df_new['data_type'] = data_type.split('.')[0] 
    df_combined = pd.concat([df_combined, df_new])

In [73]:
df_combined

,tweet_id,tweet_text,class_label,file_name,event,year,event_type,data_type,30 mtime=1582530033.707475781
0,1.065845e+18,"Camp Fire leaves over 13,000 without homes thi...",displaced_people_and_evacuations,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev,NaN
1,1.061321e+18,"So in a truly strange world, we have @RealJame...",not_humanitarian,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev,NaN
2,1.063536e+18,66 people have died and more than 600 are stil...,injured_or_dead_people,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev,NaN
3,1.062711e+18,BBC News - California wildfires: Nine dead and...,injured_or_dead_people,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev,NaN
4,1.064808e+18,Death toll in California’s #CampFire has climb...,injured_or_dead_people,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev,NaN
...,...,...,...,...,...,...,...,...,...
387,8.719806e+17,"South Korean Actress Lee Young-ae, ‘Changumi’ ...",rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train,NaN
388,8.723400e+17,Flood donations granted under North-South Brot...,rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train,NaN
389,8.701779e+17,#Inspiring Naval diving teams rescue a dog whi...,rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train,NaN
390,8.705100e+17,Norway to provide US$ 1.2 million to Sri Lanka...,rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train,NaN
391,8.704611e+17,RT @NewsArmageddon: Sri Lanka deploys more tro...,other_relevant_information,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train,NaN

In [74]:
df_combined = df_combined[['tweet_id', 'tweet_text', 'class_label', 'file_name', 'event', 'year', 'event_type', 'data_type']]

In [75]:
df_combined

,tweet_id,tweet_text,class_label,file_name,event,year,event_type,data_type
0,1.065845e+18,"Camp Fire leaves over 13,000 without homes thi...",displaced_people_and_evacuations,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev
1,1.061321e+18,"So in a truly strange world, we have @RealJame...",not_humanitarian,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev
2,1.063536e+18,66 people have died and more than 600 are stil...,injured_or_dead_people,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev
3,1.062711e+18,BBC News - California wildfires: Nine dead and...,injured_or_dead_people,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev
4,1.064808e+18,Death toll in California’s #CampFire has climb...,injured_or_dead_people,california_wildfires_2018_dev.tsv,california_wildfires_2018,2018,fire,dev
...,...,...,...,...,...,...,...,...
387,8.719806e+17,"South Korean Actress Lee Young-ae, ‘Changumi’ ...",rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train
388,8.723400e+17,Flood donations granted under North-South Brot...,rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train
389,8.701779e+17,#Inspiring Naval diving teams rescue a dog whi...,rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train
390,8.705100e+17,Norway to provide US$ 1.2 million to Sri Lanka...,rescue_volunteering_or_donation_effort,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train
391,8.704611e+17,RT @NewsArmageddon: Sri Lanka deploys more tro...,other_relevant_information,srilanka_floods_2017_train.tsv,srilanka_floods_2017,2017,flood,train

In [76]:
df_combined.to_csv('assets/df_combined.csv', index=False)